# Docker Compose YML Config

# This is the Development Local Config (Docker Compose v1.6.0 up)

version: '2'
services:
  app:
    restart: always
    build: 
      context: ./
      args:
        - ENV_TYPE=local
    # depends_on:
    #   - postgres
    #   - redis
    #   - rabbitmq
   # volumes:
   #   - ./docker/app/app:/app
    ports:
      - "8000:8000"
      - "3000:3000"
      - "3001:3001"
      - "5555:5555"
    # links:
    #   - postgres:postgres
    #   - redis:redis
    #   - rabbitmq:rabbitmq


  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
       - /var/lib/postgresql
    ports:
      - "5432:5432"


  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"


  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    # volumes:
    #   - /www/static
    # volumes_from:
    #   - app
    # links:
    #   - app:app
