# Docker Compose YML Config

# This is the Production Config (Docker Compose v1.6.0 up)


version: '2'
services:
    app:
      extends:
        file: docker-compose-common.yml
        service: app
      build: 
        context: docker/app
        args:
          - ENV_TYPE=prod
      ports:
        - "8000"
        - "3000"
        - "3001"
        - "5555"
      depends_on:
        - postgres
        - redis
        - rabbitmq
      links:
        - postgres:postgres
        - redis:redis
        - rabbitmq:rabbitmq
      env_file:
        - .env

    redis:
      extends:
        file: docker-compose-common.yml
        service: redis
      ports:
        - "6379"

    postgres:
      extends:
        file: docker-compose-common.yml
        service: postgres
      expose:
        - "5432" 
      env_file:
        - .env

    rabbitmq:
      extends:
        file: docker-compose-common.yml
        service: rabbitmq
      env_file:
        - .env

    nginx:
      extends:
        file: docker-compose-common.yml
        service: nginx
      links:
        - app:app
      volumes:
        - /www/static
      volumes_from:
        - app
      env_file:
        - .env